#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!! ......in progress.....
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

name: limesdr-osmotrx
version: 0.1.0
summary: LimeSuite + Osmo-TRX
description: LimeSuite driver, SoapySDR, UHD, Osmo-TRX
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP
    SOAPY_SDR_ROOT: $SNAP
    APPDATA: $SNAP_USER_COMMON
    UHD_MODULE_PATH: $SNAP/lib/uhd/modules

apps:

    SoapySDRUtil:
        command: SoapySDRUtil
        plugs: [network, network-bind]

    uhd-find-devices:
        command: uhd_find_devices
        plugs: [network, network-bind]

    osmo-nitb:
        command: osmo-nitb
        plugs: [network, network-bind]

    osmobts-trx:
        command: osmobts-trx
        plugs: [network, network-bind]

    osmo-trx:
        command: osmo-trx
        plugs: [network, network-bind]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    osmocombo:
        source: osmocombo
        plugin: make
        build-packages:
            - build-essential
            - libsqlite3-dev
            - libboost-all-dev
            - libmnl-dev
            - libssl-dev
            - libpcap-dev
            - libi2c-dev
            - libusb-1.0-0-dev
            - autoconf
            - libtool
            - libpcsclite-dev
            - libortp-dev
            - libdbi-dev
            - libdbd-sqlite3

    osmotrx:
        plugin: autotools
        source: https://github.com/myriadrf/osmo-trx.git
        source-branch: myriadrf/limesdr
        after: [uhd, osmocombo]

    uhd:
        plugin: cmake
        source: https://github.com/EttusResearch/uhd.git
        source-branch: maint
        source-subdir: host
        build-packages: [libboost-all-dev]
        after: [pythonmodules]
        configflags:
            - -DENABLE_MANUAL=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_MAN_PAGES=OFF
            - -DENABLE_EXAMPLES=OFF
            - -DENABLE_TESTS=OFF
            - -DENABLE_USB=OFF
            - -DENABLE_GPSD=OFF
            - -DENABLE_B100=OFF
            - -DENABLE_B200=OFF
            - -DENABLE_E100=OFF
            - -DENABLE_E300=OFF
            - -DENABLE_USRP1=OFF
            - -DENABLE_USRP2=OFF
            - -DENABLE_X300=OFF
            - -DENABLE_N230=OFF
            - -DENABLE_OCTOCLOCK=OFF

    soapyuhd:
        plugin: cmake
        source: https://github.com/pothosware/SoapyUHD.git
        source-branch: master
        after: [soapysdr, uhd]
        configflags:
             - -DUHD_ROOT=.

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        configflags:
            - -DENABLE_GUI=OFF
            - -DDOWNLOAD_IMAGES=TRUE
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    pythonmodules:
        plugin: dump
        source: .
        stage-packages:
            - python
            - python-cheetah
            - python-mako
