name: limesdr-grc
version: 0.1.0
summary: LimeSuite + GRC
description: LimeSuite driver, SoapySDR, GRC, DTV demo
confinement: strict

apps:

    gnuradio-companion:
        command: environment desktop-launch gnuradio-companion
        plugs: [network, x11, opengl, home]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        configflags:
            - -DENABLE_GUI=OFF
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    volk:
        plugin: cmake
        source: https://github.com/pothosware/volk.git
        source-branch: volk_snaps
        build-packages: [libboost-all-dev]
        after: [environment]

    gnuradio:
        plugin: cmake
        source: https://github.com/gnuradio/gnuradio.git
        source-branch: maint
        build-packages:
            - libboost-all-dev
            - libfftw3-dev
            - python-dev
            - swig
        configflags:
            - -DENABLE_TESTING=OFF
            - -DENABLE_INTERNAL_VOLK=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_SPHINX=OFF
            - -DENABLE_GR_UHD=OFF
            - -DENABLE_GR_QTGUI=OFF

        after: [desktop-gtk3, volk, environment]

    grosmosdr:
        plugin: cmake
        source: git://git.osmocom.org/gr-osmosdr
        build-packages:
            - libboost-all-dev
            - python
            - python-cheetah
            - swig
        after: [soapysdr, gnuradio, environment]

    environment:
        plugin: dump
        source: .
        organize:
            environment.sh: bin/environment
            wx.pth: usr/lib/wx/python/wx.pth
        stage-packages:
            - python
            - python-cheetah
            - python-mako
            - python-numpy
            - python-gtk2
            - python-lxml
            - python-wxgtk3.0
            - python-wxversion
