name: limesdr-grc
version: 3.7.10.1.0
summary: LimeSuite + GRC
description: LimeSuite driver, SoapySDR, GRC, DTV demo
confinement: strict

apps:

    SoapySDRUtil:
        command: environment SoapySDRUtil
        plugs: [network]

    gnuradio-companion:
        command: environment desktop-launch gnuradio-companion
        plugs: [network, network-bind, x11, opengl, home]

    gnuradio-config-info:
        command: environment gnuradio-config-info

    volk-config-info:
        command: environment volk-config-info

    volk-profile:
        command: environment volk_profile

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        configflags:
            - -DENABLE_GUI=OFF
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    volk:
        plugin: cmake
        source: https://github.com/pothosware/volk.git
        source-branch: volk_snaps
        build-packages: [libboost-all-dev, liborc-0.4-dev]
        after: [environment]

    gnuradio:
        plugin: cmake
        source: https://github.com/pothosware/gnuradio.git
        source-branch: gr_snaps
        build-packages:
            - python-dev
            - libasound2-dev
            - libboost-all-dev
            - libcodec2-dev
            - libcomedi-dev
            - libfftw3-dev
            - libfontconfig1-dev
            - libgsl-dev
            - libgsm1-dev
            - libjack-jackd2-dev
            - liblog4cpp5-dev
            - libpulse-dev
            - libqt4-dev
            - libqwt5-qt4-dev
            - libsdl1.2-dev
            - libsndfile1-dev
            - libxi-dev
            - libxrender-dev
            - libzmq3-dev
            - portaudio19-dev
        configflags:
            - -DENABLE_TESTING=OFF
            - -DENABLE_INTERNAL_VOLK=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_SPHINX=OFF
            - -DENABLE_GR_UHD=OFF
            - -DENABLE_GR_QTGUI=OFF

        after: [desktop-gtk3, volk, environment]

    grosmosdr:
        plugin: cmake
        source: git://git.osmocom.org/gr-osmosdr
        build-packages:
            - libboost-all-dev
            - python
            - python-cheetah
            - swig
        after: [soapysdr, gnuradio, environment]

    environment:
        plugin: dump
        source: .
        organize:
            environment.sh: bin/environment
            wx.pth: usr/lib/wx/python/wx.pth
        stage-packages:
            - python
            - python-opengl
            - python-cheetah
            - python-mako
            - python-numpy
            - python-scipy
            - python-gtk2
            - python-lxml
            - python-wxgtk3.0
            - python-wxversion
            - python-zmq
            - python-qwt5-qt4
            - swig
