name: limesdr-gqrx
version: 2.6.0
summary: LimeSuite + GQRX
description: LimeSuite driver, SoapySDR, GQRX
confinement: strict

apps:

    SoapySDRUtil:
        command: environment SoapySDRUtil
        plugs: [network]

    gqrx:
        command: environment desktop-launch gqrx
        plugs: [network, x11, pulseaudio, opengl, home]

    gnuradio-config-info:
        command: environment gnuradio-config-info

    volk-config-info:
        command: environment volk-config-info

    volk_profile:
        command: environment volk_profile

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        configflags:
            - -DENABLE_GUI=OFF
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    volk:
        source: https://github.com/pothosware/volk.git
        source-branch: volk_snaps
        build-packages: [libboost-all-dev]
        after: [environment]

    gnuradio:
        plugin: cmake
        source: https://github.com/gnuradio/gnuradio.git
        source-branch: maint
        build-packages:
            - libboost-all-dev
            - libfftw3-dev
        configflags:
            - -DENABLE_PYTHON=OFF
            - -DENABLE_TESTING=OFF
            - -DENABLE_INTERNAL_VOLK=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_SPHINX=OFF
            - -DENABLE_GR_QTGUI=OFF
            - -DENABLE_GR_WXGUI=OFF
        after: [volk]

    grosmosdr:
        plugin: cmake
        source: git://git.osmocom.org/gr-osmosdr
        build-packages: [libboost-all-dev]
        configflags:
            - -DENABLE_PYTHON=OFF
        after: [soapysdr, gnuradio]

    gqrx:
        plugin: cmake
        source: https://github.com/csete/gqrx.git
        build-packages: [qtbase5-dev]
        after: [grosmosdr, desktop-qt5]

    environment:
        plugin: dump
        source: .
        organize:
            environment.sh: bin/environment
        stage-packages:
            - python
            - python-cheetah
            - python-mako
