name: limesuite
version: 17.01.0.0
summary: LimeSuite apps
description: LimeSuite command line utility and Graphical eval app.
confinement: strict

apps:
    LimeUtil:
        command: environment LimeUtil
        plugs: [network, home]

    LimeSuiteGUI:
        command: environment desktop-launch LimeSuiteGUI
        plugs: [network, home, x11, opengl]
parts:

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        after: [desktop-gtk3]
        configflags:
            - -DENABLE_SOAPY_LMS7=OFF
            - -DDOWNLOAD_IMAGES=TRUE
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev
            - libwxgtk3.0-dev
            - freeglut3-dev

    environment:
        plugin: dump
        source: .
        organize:
            environment.sh: bin/environment
