name: soapysdr-server
version: 0.5.3.0
summary: SoapySDR server
description: SoapySDR server that binds on snap install
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP
    SOAPY_SDR_ROOT: $SNAP

apps:
    server:
        command: SoapySDRServer --bind
        daemon: simple
        plugs: [network, network-bind]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        configflags:
            - -DENABLE_GUI=OFF
            - -DDOWNLOAD_IMAGES=TRUE
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev
