name: soapysdr-server
version: 0.1.0
summary: SoapySDR server
description: SoapySDR server that binds on snap install
confinement: strict

apps:
    server:
        command: bin/SoapySDRServer --bind
        daemon: simple
        plugs: [network, network-bind]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DSOAPY_SDR_ROOT_ENV=SNAP
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        configflags:
            - -DENABLE_LMS7_GUI=OFF
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev
